### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'app_review/app_review-Swift.h' file not found

### ISSUE THREAD

**Issue by ChurikiTenna** [fluttercommunity/app_review#73]
When I try to build, it fails with Lexical or Preprocessor Issue.

I tried flutter clean, deleting profile.lock and podfiles.

Device: Phone 11, iOS 16.2

pubspec.yaml
```
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  app_review: ^2.1.1
  app_tracking_transparency: ^2.0.3
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_analytics: 10.0.3
  firebase_core: 2.1.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.0+2
  flutter_screenutil: ^5.4.0
  google_fonts: ^2.3.1
  google_mlkit_digital_ink_recognition: ^0.6.0
  google_mobile_ads: ^2.3.0
  provider: ^6.0.2
  purchases_flutter: ^3.10.0
  shared_preferences: ^2.0.13
  syncfusion_flutter_charts: ^20.1.50
  url_launcher: ^6.0.20
```

Error
```
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'app_review/app_review-Swift.h' file not found
/Users/tenna/.pub-cache/hosted/pub.dev/app_review-2.1.2+1/ios/Classes/AppReviewPlugin.m:1:8
```
